spring:
  application:
    name: PDV_APi

# informacoes do banco, utilizando variaveis de ambiente
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_SENHA}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      dll-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
